import { createReferenceClientFromRequest as createClientFromRequest } from '../../runtime/referenceClient';

Deno.serve(async (req) => {
  try {
    const atlasRuntime = createClientFromRequest(req);
    const { summary = "", recipients = [] } = await req.json().catch(() => ({}));

    // Recipients default to the sales management team = all admin (manager) users
    let toList = Array.isArray(recipients) ? recipients.filter(Boolean) : [];
    if (toList.length === 0) {
      try {
        const users = await atlasRuntime.asServiceRole.entities.User.list();
        toList = users.filter((u) => u.role === "admin").map((u) => u.email).filter(Boolean);
      } catch (e) {
        toList = [];
      }
    }

    let emailed = 0;
    const subject = `Weekly Sales Report — ${new Date().toLocaleDateString("en-US")}`;
    const body = `${summary || "Weekly sales report (no summary generated)."}\n\n— Generated by the Weekly Sales Report workflow`;

    for (const email of toList) {
      try {
        await atlasRuntime.asServiceRole.integrations.Core.SendEmail({
          to: email,
          subject,
          body,
          from_name: "Sales Reports"
        });
        emailed++;
      } catch (e) {
        // skip individual failures, continue with remaining recipients
      }
    }

    return Response.json({ recipients: toList, emailed });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});